In [13]:
import pandas as pd

Read the clean data we need from the ETL process

In [14]:
book_dim = pd.read_csv('../ssis_data/book_dim.csv')
category_dim = pd.read_csv('../ssis_data/category_dim.csv')
fact_table = pd.read_csv('../ssis_data/rbook_fact.csv')

Merge the book_dim and fact_table on the id_book column

In [15]:
# Merge the book_dim and fact_table on the id_book column
data = pd.merge(book_dim, fact_table, left_on='id_book', right_on='Book')
data

id_book                                        label_title  \
0           49  Oliver Byrne's Elements of Euclid: The First S...   
1           54  My Grandmother's Hands: Racialized Trauma and ...   
2           90  Brickwork Projects for Patio & Garden: Designs...   
3          106  Beyond the Back Yard: Train Your Dog to Listen...   
4          168  Fundamentals of Project Management, Sixth Edition   
...        ...                                                ...   
83699   124178  Dominance and Submission: : The Blue Oyster Cu...   
83700   126715                                          Jura Wine   
83701   129242  A Quiet Mind to Suffer With: Mental Illness, T...   
83702   130082  Surviving and Thriving in Middle School Genera...   
83703   130457  Drinkable Rivers: How the river became my teacher   

       label_reviews  label_isKindleUnlimited  label_isBestSeller  \
0                  0                    False               False   
1                  0                    False               False   
2                  0                    False               False   
3                  0                    False               False   
4                  0                    False               False   
...              ...                      ...                 ...   
83699              1                    False               False   
83700              1                    False               False   
83701              1                    False               False   
83702              1                    False               False   
83703              1                    False               False   

       label_isEditorsPick  label_isGoodReadsChoice    Book  Author  \
0                    False                    False      49    5242   
1                    False                    False      54   41771   
2                    False                    False      90   24368   
3                    False                    False     106   17027   
4                    False                    False     168   35183   
...                    ...                      ...     ...     ...   
83699                False                    False  124178   46042   
83700                False                    False  126715   71601   
83701                False                    False  129242   33269   
83702                False                    False  130082   49098   
83703                False                    False  130457   41713   

       PublishedDate  Category  SoldBy  Rating  price  
0               5969        26      22     4.4   9.99  
1               2527        21      22     4.8   9.99  
2               5488        10      22     4.2   9.99  
3               6092         8      22     4.6   9.99  
4               7021         3       2     4.8   9.99  
...              ...       ...     ...     ...    ...  
83699           1568         1      22     5.0   9.99  
83700           5090        31      22     5.0   9.99  
83701           3886        24      22     5.0   9.99  
83702           5919         9      22     5.0   9.99  
83703           1709        31      22     5.0   9.99  

[83704 rows x 14 columns]

Now we will merge the data and category_dim on the id_category column

In [16]:
# Merge the data and category_dim on the id_category column
data = pd.merge(data, category_dim, left_on='Category', right_on='id_category')
data   

id_book                                        label_title  \
0           49  Oliver Byrne's Elements of Euclid: The First S...   
1         1529  THE ILLUSTRATED THEORY OF EVERYTHING: The Orig...   
2         1589  The Circadian Code: Lose Weight, Supercharge Y...   
3         1851  The Medical School Interview: Winning Strategi...   
4         1909                          Complexity: A Guided Tour   
...        ...                                                ...   
83699    71631  Disney Tim Burton's The Nightmare Before Chris...   
83700    76574  Frank Miller's Sin City Volume 1: The Hard Goo...   
83701    26071      Hellboy Omnibus Volume 1: Seed of Destruction   
83702   102595  George and Harold's Epic Comix Collection Vol,...   
83703    45733                     Enough Space for Everyone Else   

       label_reviews  label_isKindleUnlimited  label_isBestSeller  \
0                  0                    False               False   
1                  0                    False               False   
2                  0                    False               False   
3                  0                    False               False   
4                  0                    False               False   
...              ...                      ...                 ...   
83699            584                    False               False   
83700            715                    False               False   
83701           1734                    False               False   
83702            780                    False               False   
83703              2                     True               False   

       label_isEditorsPick  label_isGoodReadsChoice    Book  Author  \
0                    False                    False      49    5242   
1                    False                    False    1529   64768   
2                    False                    False    1589   61803   
3                    False                    False    1851   61030   
4                    False                    False    1909   47534   
...                    ...                      ...     ...     ...   
83699                False                    False   71631   36382   
83700                False                    False   76574   22734   
83701                False                    False   26071   49439   
83702                False                    False  102595   61891   
83703                False                    False   45733      17   

       PublishedDate  Category  SoldBy  Rating  price  id_category  \
0               5969        26      22     4.4   9.99           26   
1               2347        26      22     4.5   9.99           26   
2               1910        26       9     4.6   9.99           26   
3               2411        26      22     4.4   9.99           26   
4               4140        26      22     4.5   9.99           26   
...              ...       ...     ...     ...    ...          ...   
83699           2940         5      28     4.7   0.00            5   
83700           6492         5      28     4.6   0.00            5   
83701           4251         5       9     4.8  14.99            5   
83702           2715         5       3     4.8   5.99            5   
83703           1293         5      22     4.7   9.99            5   

       label_category  
0      Science & Math  
1      Science & Math  
2      Science & Math  
3      Science & Math  
4      Science & Math  
...               ...  
83699          Comics  
83700          Comics  
83701          Comics  
83702          Comics  
83703          Comics  

[83704 rows x 16 columns]

Let's now see the distribution of the price

In [17]:
data['price'].describe()

count    83704.000000
mean        18.491458
std         25.557160
min          0.000000
25%          8.260000
50%         11.990000
75%         16.990000
max        682.000000
Name: price, dtype: float64

We can see that for prices above 16.99, the number of books is considered to be expensive. 
For prices below 11.99, the number of books is considered to be cheap. 

So, we will create two new columns, is_cheap and is_expensive, to indicate whether a book is cheap or expensive.
Also, we will create a new column, is_highly_rated, to indicate whether a book is highly rated or not and we will consider a book to be highly rated if its rating is greater than 4.5 based on our observations.

In [18]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

# Preprocessing
data['is_highly_rated'] = data['Rating'] > 4.5
data['is_cheap'] = data['price'] < 11.99
data['is_expensive'] = data['price'] >= 16.99

We now proceed to one hot encode the category columns and keep only the relevant columns.

In [19]:
# One hot encode the category columns
categories = data[['label_category']]
categories = pd.get_dummies(categories, columns=['label_category'])
categories

label_category_Arts & Photo graphy  \
0                                   False   
1                                   False   
2                                   False   
3                                   False   
4                                   False   
...                                   ...   
83699                               False   
83700                               False   
83701                               False   
83702                               False   
83703                               False   

       label_category_Biographies & Memoirs  label_category_Business & Money  \
0                                     False                            False   
1                                     False                            False   
2                                     False                            False   
3                                     False                            False   
4                                     False                            False   
...                                     ...                              ...   
83699                                 False                            False   
83700                                 False                            False   
83701                                 False                            False   
83702                                 False                            False   
83703                                 False                            False   

       label_category_Children's eBooks  label_category_Comics  \
0                                 False                  False   
1                                 False                  False   
2                                 False                  False   
3                                 False                  False   
4                                 False                  False   
...                                 ...                    ...   
83699                             False                   True   
83700                             False                   True   
83701                             False                   True   
83702                             False                   True   
83703                             False                   True   

       label_category_Computers & Technology  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
...                                      ...   
83699                                  False   
83700                                  False   
83701                                  False   
83702                                  False   
83703                                  False   

       label_category_Cookbooks, Food & Wine  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
...                                      ...   
83699                                  False   
83700                                  False   
83701                                  False   
83702                                  False   
83703                                  False   

       label_category_Crafts, Hobbies & Home  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
...                                      ...   
83699                                  False   
83700                                  False   
83701                                  False   
83702                                  False   
83703                         

We choose the following columns to be relevant for our analysis:
- is_highly_rated
- is_cheap
- is_expensive
- label_isBestSeller
- label_isEditorsPick
- label_isGoodReadsChoice
- label_isKindleUnlimited
- categories

In [20]:
# Select relevant columns
relevant_data = data[['is_highly_rated', 'is_cheap', 'is_expensive', 'label_isBestSeller',
                      'label_isEditorsPick', 'label_isGoodReadsChoice', 'label_isKindleUnlimited']]
relevant_data

is_highly_rated  is_cheap  is_expensive  label_isBestSeller  \
0                False      True         False               False   
1                False      True         False               False   
2                 True      True         False               False   
3                False      True         False               False   
4                False      True         False               False   
...                ...       ...           ...                 ...   
83699             True      True         False               False   
83700             True      True         False               False   
83701             True     False         False               False   
83702             True      True         False               False   
83703             True      True         False               False   

       label_isEditorsPick  label_isGoodReadsChoice  label_isKindleUnlimited  
0                    False                    False                    False  
1                    False                    False                    False  
2                    False                    False                    False  
3                    False                    False                    False  
4                    False                    False                    False  
...                    ...                      ...                      ...  
83699                False                    False                    False  
83700                False                    False                    False  
83701                False                    False                    False  
83702                False                    False                    False  
83703                False                    False                     True  

[83704 rows x 7 columns]

In [21]:
# Append the categories columns to the relevant data
relevant_data = pd.concat([relevant_data, categories], axis=1)
relevant_data

is_highly_rated  is_cheap  is_expensive  label_isBestSeller  \
0                False      True         False               False   
1                False      True         False               False   
2                 True      True         False               False   
3                False      True         False               False   
4                False      True         False               False   
...                ...       ...           ...                 ...   
83699             True      True         False               False   
83700             True      True         False               False   
83701             True     False         False               False   
83702             True      True         False               False   
83703             True      True         False               False   

       label_isEditorsPick  label_isGoodReadsChoice  label_isKindleUnlimited  \
0                    False                    False                    False   
1                    False                    False                    False   
2                    False                    False                    False   
3                    False                    False                    False   
4                    False                    False                    False   
...                    ...                      ...                      ...   
83699                False                    False                    False   
83700                False                    False                    False   
83701                False                    False                    False   
83702                False                    False                    False   
83703                False                    False                     True   

       label_category_Arts & Photo graphy  \
0                                   False   
1                                   False   
2                                   False   
3                                   False   
4                                   False   
...                                   ...   
83699                               False   
83700                               False   
83701                               False   
83702                               False   
83703                               False   

       label_category_Biographies & Memoirs  label_category_Business & Money  \
0                                     False                            False   
1                                     False                            False   
2                                     False                            False   
3                                     False                            False   
4                                     False                            False   
...                                     ...                              ...   
83699                                 False                            False   
83700                                 False                            False   
83701                                 False                            False   
83702                                 False                            False   
83703                                 False                            False   

       ...  label_category_Politics & Social Sciences  \
0      ...                                      False   
1      ...                                      False   
2      ...                                      False   
3      ...                                      False   
4      ...                                      False   
...    ...                                        ...   
83699  ...                                      False   
83700  ...                                      False   
83701  ...                                      False   
83702  ...                                      False   
83703  ...                                      False   

       label_categ

We now proceed to apply the Apriori algorithm to find the frequent itemsets and the association rules.

In [22]:
# Convert DataFrame into a list of lists for TransactionEncoder
transactions = relevant_data.apply(lambda row: row.index[row].tolist(), axis=1)

# TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

# Applying the Apriori algorithm
frequent_itemsets = apriori(df, min_support=0.04, use_colnames=True, low_memory=False)

# Displaying the frequent itemsets
frequent_itemsets

support                                           itemsets
0   0.542065                                         (is_cheap)
1   0.244696                                     (is_expensive)
2   0.492354                                  (is_highly_rated)
3   0.044657               (label_category_Arts & Photo graphy)
4   0.057775             (label_category_Biographies & Memoirs)
5   0.054741                 (label_category_Children's eBooks)
6   0.053080            (label_category_Computers & Technology)
7   0.053582            (label_category_Cookbooks, Food & Wine)
8   0.051682            (label_category_Crafts, Hobbies & Home)
9   0.046521              (label_category_Education & Teaching)
10  0.058790      (label_category_Engineering & Transportation)
11  0.048158                               (label_category_Law)
12  0.054729         (label_category_Parenting & Relationships)
13  0.042925        (label_category_Politics & Social Sciences)
14  0.060810                    (label_category_Science & Math)
15  0.050189                            (label_category_Travel)
16  0.050010                              (label_isEditorsPick)
17  0.155560                          (label_isKindleUnlimited)
18  0.257754                        (is_highly_rated, is_cheap)
19  0.045159       (label_category_Children's eBooks, is_cheap)
20  0.142072                (is_cheap, label_isKindleUnlimited)
21  0.125753                    (is_highly_rated, is_expensive)
22  0.043475  (label_category_Children's eBooks, is_highly_r...
23  0.062363         (is_highly_rated, label_isKindleUnlimited)
24  0.054693  (is_highly_rated, is_cheap, label_isKindleUnli...

In [23]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3).sort_values(by='confidence', ascending=False)
rules

antecedents                  consequents  \
3                   (label_isKindleUnlimited)                   (is_cheap)   
7  (is_highly_rated, label_isKindleUnlimited)                   (is_cheap)   
2          (label_category_Children's eBooks)                   (is_cheap)   
5          (label_category_Children's eBooks)            (is_highly_rated)   
0                           (is_highly_rated)                   (is_cheap)   
4                              (is_expensive)            (is_highly_rated)   
1                                  (is_cheap)            (is_highly_rated)   
6                   (label_isKindleUnlimited)            (is_highly_rated)   
8         (is_cheap, label_isKindleUnlimited)            (is_highly_rated)   
9                   (label_isKindleUnlimited)  (is_highly_rated, is_cheap)   

   antecedent support  consequent support   support  confidence      lift  \
3            0.155560            0.542065  0.142072    0.913294  1.684842   
7            0.062363            0.542065  0.054693    0.877011  1.617909   
2            0.054741            0.542065  0.045159    0.824967  1.521898   
5            0.054741            0.492354  0.043475    0.794195  1.613056   
0            0.492354            0.542065  0.257754    0.523513  0.965775   
4            0.244696            0.492354  0.125753    0.513915  1.043791   
1            0.542065            0.492354  0.257754    0.475503  0.965775   
6            0.155560            0.492354  0.062363    0.400891  0.814233   
8            0.142072            0.492354  0.054693    0.384965  0.781886   
9            0.155560            0.257754  0.054693    0.351586  1.364039   

   leverage  conviction  zhangs_metric  
3  0.057748    5.281464       0.481352  
7  0.020888    3.723398       0.407320  
2  0.015486    2.616283       0.362785  
5  0.016523    2.466632       0.402068  
0 -0.009134    0.961064      -0.065254  
4  0.005276    1.044356       0.055545  
1 -0.009134    0.967872      -0.071828  
6 -0.014228    0.847335      -0.212709  
8 -0.015257    0.825393      -0.245371  
9  0.014597    1.144711       0.316048